language: java
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
cache:
  directories:
    - $HOME/.m2
install:
  - export CODACY_COVERAGE_REPORTER_VERSION=2.0.0
  - export CODACY_PROJECT_TOKEN=7b7633aa2c1f4477ade4b81986fbe084
  - wget https://github.com/codacy/codacy-coverage-reporter/releases/download/${CODACY_COVERAGE_REPORTER_VERSION}/codacy-coverage-reporter-${CODACY_COVERAGE_REPORTER_VERSION}-assembly.jar
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - mvn clean install -Dapp.log.level.test=info -Ddatabase.postgresql=true
after_script:
  - mvn jacoco:report
  - java -cp codacy-coverage-reporter-${CODACY_COVERAGE_REPORTER_VERSION}-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml
